Vagrant.configure(2) do |config|
  config.vm.box = 'generic/alpine39'
  config.ssh.forward_agent = true

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision 'shell', inline: 'uname -a'
  config.vm.provision 'shell', inline: 'cat /etc/alpine-release'
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
  config.vm.provision 'shell', inline: 'apk add util-linux; lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL'
  config.vm.provision 'shell', inline: 'df -h'
  config.vm.provision 'shell', path: 'setup.sh'
end
