# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "~/git/newsuk", "/src/"
  config.vm.network :forwarded_port, guest: 8080, host: 4567

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.define "main" do |app|
    app.vm.hostname = "main.dev"
    config.vm.box = "ubuntu/xenial64"
    app.vm.network :private_network, ip: "192.168.60.7"
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # Run commands as root.
    ansible.become = true
    ansible.become_user = "root"
  end
end
