---
- hosts: void
  remote_user: vagrant
  pre_tasks:
    - name: 'install python'
      raw: pkg_add python3

  vars_files:
    - vars.yaml
  tasks:
    - name: System Upgrade
      xbps:
        update_cache: true
        upgrade: true

    - name: Ensure directories
      file:
        path: "{{ src_home }}"
        state: directory
        owner: "{{ user }}"

    - name: Alt Install
      shell: |
         pkg_add {{ item }}
      with_items:
        - "{{ cli }}"
      become: true
      become_method: sudo

    - name: Clone Dotfiles
      git:
        repo: https://github.com/hmgibson23/snippets.git
        dest: "{{home}}/snippets"

    - name: Clone Tools
      git:
        repo: https://github.com/hmgibson23/tools.git
        dest: "{{src_home}}/tools"

    - name: Fonts
      git:
        repo: https://github.com/ryanoasis/nerd-fonts.git
        dest: "{{src_home}}/nerd-fonts"
        force: yes

    - name: Siji
      git:
        repo: https://github.com/stark/siji
        dest: "{{src_home}}/siji"
        force: yes

    - name: Suckless
      git:
        repo: https://github.com/hmgibson23/suckless.git
        dest: "{{src_home}}/suckless"
        force: yes

    - name: Siji Font
      shell: |
        cd {{src_home}}/siji && ./install ~/.local/share/fonts

# git clone https://github.com/lcpz/lain.git ~/.config/awesome/lain
# git@github.com:tryone144/compton.git
# https://github.com/krypt-n/bar
# git@github.com:troydm/xmonad-dbus.git

    - name: Install Fonts
      shell: |
        cd {{src_home}}/nerd-fonts
        ./install.sh Hack
        ./install.sh Inconsolata
        ./install.sh Terminus
        ./install.sh SourceCodePro
        ./install.sh Meslo

    - name: Build simple terminal
      shell: |
        cd {{src_home}} && rm -f ./st/config.def.h
        ln -s {{src_home}}/snippets/config.def.h {{src_home}}/st/config.def.h
        cd ./st && make

    - name: Simple Terminal Install
      shell: |
        cd  {{ src_home }}/st && make install
      become: yes
      become_method: sudo

    - name: NetworkManager
      shell: |
        ln -s /etc/sv/NetworkManager /var/service
        ln -s /etc/sv/dbus /var/service
      become: yes
      become_method: sudo

    - name: Enable DM and BSPWM
      shell: |
        ln -s /etc/sv/lxdm /var/service
      become: true
      become_method: sudo

    - name: BB Setup
      copy:
        src: ./etc/xorg.conf.nvidia
        dest: /etc/bumblebee/xorg.conf.nvidia

    - name: Intel BB
      copy:
        src: ./etc/20-intel.conf
        dest: /usr/share/X11/xorg.conf.d/20-intel.conf

    - name: Vagrant plugins
      shell: |
        vagrant plugin install vagrant-mutate
        vagrant plugin install vagrant-libvirt
