# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "SierraX/openbsd-6.3"
  config.vm.box_version = "1.0.0"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.define "void" do |app|
    app.vm.hostname = "main.dev"
    config.vm.box = "SierraX/openbsd-6.3"
    app.vm.network :private_network, ip: "10.0.3.2"
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
