VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key       = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "256"]
  end

  config.vm.define "vault-1" do |app|
    app.vm.hostname = "vault-1.dev"
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.60.8"
  end

  config.vm.define "vault-2" do |app|
    app.vm.hostname = "vault-2.dev"
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.60.9"
  end
end
