#!/usr/bin/env sh

PASS=$(gpg -qd ~/.mutt/password.gpg)
OUT=$(mail imaps://imap.gmail.com gibsonhugo@gmail.com $PASS)

RES=$( echo $OUT | cut -d "(" -f2 | cut -d ")" -f1 | grep -o '.$')

echo $RES
#  printf ''
