# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  # config.vm.synced_folder "~/git", "/src/", type: '9p', disabled: false, accessmode: "squash", owner: "hugo"
  config.vm.synced_folder "~/git", "/src/", type: "sshfs"
  #, type: "nfs", nfs_version: 4, "nfs_udp": false, mount_options: ["rw", "vers=4", "tcp", "nolock"], allow_ip: "all"
  config.vm.network :forwarded_port, guest: 8080, host: 4567
  config.vm.box_check_update = false
  config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name="libvirt-shared"
    libvirt.memory = 512
    libvirt.graphics_type = "none"
  end

  config.vm.define "arch" do |app|
    app.vm.hostname = "arch.dev"
    config.vm.box = "archlinux/archlinux"
    app.vm.network :private_network, ip: "10.0.1.10"
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # Run commands as root.
    ansible.become = true
    ansible.become_user = "root"
  end
end
